version: '3.5'

services:
  php:
    image: composer:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge